### ISSUE TITLE
Add suporte to clang 11.0.2 (clang-r383902b)

### ISSUE THREAD

**Issue by brunorolak** [Wave-Project/prebuilts_clang_host_linux-x86#1]
Hello, I'm trying to compile the ROM, but there is no support for clang 11.0.2 (r383902b), even when setting the FLAG in BoardConfig: TARGET_KERNEL_CLANG_VERSION := r383902b, it continues to compile using version 12.0.6 (r416183c) , my kernel is 3.18, and it uses clang 11 still.

Log about error: https://hastebin.com/anucorovej.sql

**Comment by adithya2306** [comment]
You can either fix your kernel (should be easy) to build and boot with clang 12, or use this repo:
https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6573524

**Comment by brunorolak** [comment]
> You can either fix your kernel (should be easy) to build and boot with clang 12, or use this repo:
> https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-6573524

I used these repo, cloned into clang folder and setup flag on boardconfig, but the builder forces to use clang 12 all times. really I have tried all things, the problem is source script forces to use clang 12
